In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
unit_dispatches_dataframe = pd.read_excel("unit_dispatches_last_30_days.xlsx", index_col=0)
incidents_dataframe = pd.read_excel("unit_dispatches_last_30_days.xlsx", index_col=0)

In [3]:
unit_dispatches_dataframe

      unit dispatched arrived in_service  is_in_charge incident_number
0      A10      12:55     NaN      13:07          True      F260019908
1      E27      12:55   13:05      13:38         False      F260019908
2      E33      12:55   13:03      13:19         False      F260019908
3      H98      12:59     NaN      13:07         False      F260019908
4      A14      12:51   12:56      13:22          True      F260019906
...    ...        ...     ...        ...           ...             ...
14027   R1      00:36   00:43      00:51         False      F260005146
14028  E31      00:28   00:33      00:51          True      F260005144
14029  E25      00:18   00:20      00:30          True      F260005141
14030  E25      00:01   00:09      00:18          True      F260005139
14031  L10      00:01   00:06      00:15         False      F260005139

[14032 rows x 6 columns]

In [4]:
unit_dispatches_dataframe['unit'].value_counts()[:10]

unit
A2     486
A25    483
A5     461
A10    460
E2     385
E25    374
M1     367
E17    345
M10    334
E10    327
Name: count, dtype: int64

I want to add two new columns to `unit_dispatches_dataframe`. `time_in_transit` should be the difference between `dispatched` and `arrived`, `NaN` if `arrived` is `NaN`. `time_on_site` should be the difference between `arrived` and `in_service`, `NaN` if `arrived` is `NaN`.

In [5]:
def calculate_time_delta(time1, time2):
    if pd.isna(time1) or pd.isna(time2):
        return float('nan')
    time1_hours, time1_minutes = [int(value) for value in time1.split(":")]
    time1_total_minutes = time1_minutes + time1_hours * 60
    time2_hours, time2_minutes = [int(value) for value in time2.split(":")]
    if time2_hours == 0 and time1_hours != 0: 
        # If time1 is 23:50 and time2 is 1:05, this will fail, need a more general solution
        time2_hours = 24
    time2_total_minutes = time2_minutes + time2_hours * 60
    return abs(time1_total_minutes - time2_total_minutes)

In [6]:
unit_dispatches_dataframe['time_in_transit'] = unit_dispatches_dataframe.apply(
    lambda row : calculate_time_delta(
        row['dispatched'],
        row['arrived']
    ), axis=1
)

In [7]:
unit_dispatches_dataframe['time_on_site'] = unit_dispatches_dataframe.apply(
    lambda row : calculate_time_delta(
        row['arrived'],
        row['in_service']
    ), axis=1
)

In [8]:
unit_dispatches_dataframe['time_assigned'] = unit_dispatches_dataframe.apply(
    lambda row : calculate_time_delta(
        row['dispatched'],
        row['in_service']
    ), axis=1
)

In [9]:
pd.set_option('display.max_rows', None)

unit_dispatches_dataframe

            unit dispatched arrived in_service  is_in_charge incident_number  \
0            A10      12:55     NaN      13:07          True      F260019908
1            E27      12:55   13:05      13:38         False      F260019908
2            E33      12:55   13:03      13:19         False      F260019908
3            H98      12:59     NaN      13:07         False      F260019908
4            A14      12:51   12:56      13:22          True      F260019906
5             H2      12:42   13:01      13:48          True      F260019902
6            A14      12:41     NaN      12:45          True      F260019900
7            H98      12:44     NaN      12:45         False      F260019900
8            E25      12:40   12:51      12:52          True      F260019899
9            E40      12:40   12:46      12:57          True      F260019897
10           L12      12:34   12:37      12:59          True      F260019893
11           M28      12:35   12:39      13:48         False      F260019893
12           E16      12:34   12:38      13:02          True      F260019892
13            E8      12:32     NaN      12:38          True      F260019890
14            L3      12:24   12:27      12:59         False      F260019887
15           M10      12:24   12:31      13:21          True      F260019887
16           E25      12:19   12:24      12:35          True      F260019884
17           E39      12:15   12:26      12:38          True      F260019883
18            E6      12:13   12:19      12:30          True      F260019881
19           A25      12:17   12:23      12:29          True      F260019880
20           E18      12:04   12:10      12:16          True      F260019877
21            E9      12:03   12:06      12:28          True      F260019874
22           E17      12:02   12:05      12:19          True      F260019869
23           M17      12:02   12:06      12:20         False      F260019869
24           E41      12:00   12:05      12:35          True      F260019868
25            L3      11:59   12:03      12:20          True      F260019866
26           A25      11:54   11:58      12:08          True      F260019864
27           A10      11:46   12:00      12:15         False      F260019859
28            M1      11:46   11:49      12:17          True      F260019859
29            E2      11:39   11:46      11:53          True      F260019856
30           E33      11:34   11:38      11:48          True      F260019853
31            H1      11:31   11:42      12:33          True      F260019849
32           A25      11:25   11:29      11:34          True      F260019846
33           MIH      11:23     NaN      11:26          True      F260019845
34            E8      11:18     NaN      11:42         False      F260019843
35            L6      11:16     NaN      11:18          True      F260019843
36            E9      11:14   11:18      11:47         False      F260019841
37            L8      11:12     NaN      11:14          True      F260019841
38            L4      11:10   11:13      11:16          True      F260019839
39            L3      11:07   11:10      11:17          True      F260019838
40            E8      11:03   11:08      11:17          True      F260019837
41         AIR10      11:00     NaN      11:04         False      F260019835
42            B4      11:00     NaN      11:04         False      F260019835
43            B6      11:00     NaN      11:04         False      F260019835
44        DECON1      11:00     NaN      11:04         False      F260019835
45           E10      11:00     NaN      11:04          True      F260019835
46           E17      11:00     NaN      11:04         False      F260019835
47           E27      11:00     NaN      11:04         False      F260019835
48            E9      11:00   11:04      11:14         False      F260019835
49          HAZ1      11:00     NaN      11:04         False      F260019835
50            L1      11:00     NaN      11:03         False      F260019835
51            L8      11:00   11:05      11:09         False      F260019835
52           M18      11:00     NaN      11:04         False      F260019835
53         SAFT2      11:00     NaN      11:04         False      F260019835
54            E5      11:02   11:07      11:52          True      F260019834
55           M10      11:17   11:41      11:51         False      F260019834
56           M17      11:16     NaN      11:16         False      F260019834
57            E2      10:51   10:58      11:08          True      F260019832
58           E32      10:50   10:58      11:23          True      F260019831
59           A25      10:51     NaN      10:55         False      F260019830
60           E25      10:49     NaN      10:51         False      F260019830
61            E5      10:48     NaN      10:49          True      F260019830
62           A10      10:47   10:50      11:12         False      F260019829
63           M28      10:47     NaN      10:56          True      F260019829
64            L9      10:41   10:48      11:02          True      F260019827
65            E5      10:40     NaN      10:43          True      F260019826
66            E6      10:42   10:48      11:08         False      F260019826
67           E31      10:39   10:47      11:07          True      F260019824
68           E24      10:35   10:39      11:03         False      F260019823
69           M28      10:35     NaN      10:43          True      F260019823
70      NOR-M163      10:40   10:52      13:47         False      F260019823
71           E17      10:35   10:40      10:47          True      F260019822
72           E16      10:35     NaN      10:39         False      F260019821
73           E38      10:39   10:43      11:02         False      F260019821
74           M17      10:35   10:46      11:00          True      F260019821
75            E2      10:33   10:37      10:43          True      F260019820
76            M1      10:31   10:40      11:27         False      F260019819
77           M17      10:29     NaN      10:31         False      F260019819
78            R1      10:27   10:30      10:56          True      F260019819
79           A25      10:21   10:27      10:48         False      F260019815
80            M1      10:29     NaN      10:30         False      F260019815
81           M10      10:21     NaN      10:24          True      F260019815
82           M17      10:24     NaN      10:29         False      F260019815
83           A10      10:21   10:33      10:45          True      F260019816
84           E30      10:18   10:22      10:45         False      F260019814
85            M1      10:18     NaN      10:28          True      F260019814
86            E5      10:17   10:21      10:30          True      F260019813
87            E8      10:17   10:22      10:39          True      F260019812
88           E41      10:17   10:22      11:01          True      F260019811
89           E38      10:26   10:31      10:38          True      F260019809
90           E13      10:13   10:17      10:52          True      F260019808
91            M1      10:13     NaN      10:15         False      F260019808
92           M10      10:15     NaN      10:20         False      F260019808
93           M10      10:24   10:30      11:17         False      F260019808
94           L13      10:09   10:14      10:54          True      F260019807
95           M32      10:22   10:28      10:49         False      F260019807
96           E26      10:04   10:07      10:23          True      F260019804
97           A10      10:04     NaN      10:07          True      F260019805
98           A25      10:02   10:07      10:13         False      F260019802
99           L10      09:59     NaN      10:02          True      F260019802
100          E13      09:57   10:02      10:08         False      F260019800
101          E25      09:57   10:00      10:30         False      F260019800
102          H99      10:00   10:03      10:45         False      F260019800
103          M10      09:57   10:03      10:15          True      F260019800
104          E38      09:54   09:58      10:05          True      F260019799
105           E2      09:52   09:57      10:09          True      F260019798
106          E35      09:49   09:52      10:21         False      F260019796
107          M18      09:49   09:57      10:54          True      F260019796
108          E37      09:47   09:51      09:54          True      F260019795
109          E17      09:46   09:50      10:01          True      F260019794
110          E30      09:41   09:46      10:17         False      F260019791
111           E6      09:40   09:44      10:42          True      F260019791
112          M28      09:41   09:44      10:30         False      F260019791
113          A25      09:37   10:01      10:02          True      F260019789
114           E5      09:22   09:27      09:48          True      F260019786
115           E2      09:20   09:24      09:36          True      F260019784
116          E35      09:17   09:21      09:41         False      F260019783
117          M18      09:17     NaN      09:25          True      F260019783
118          L10      09:14   09:14      09:23          True      F260019781
119          E30      09:09   09:13      09:28          True      F260019780
120           B4      09:09     NaN      09:14         False      F260019779
121          E18      09:09   09:12      09:14          True      F260019779
122           E9      09:09     NaN      09:15         False      F260019779
123           L8      09:09     NaN      09:15         False      F260019779
124          E32      09:05   09:05      09:12          True      F260019777
125          E25      08:55   09:00      09:19          True      F260019772
126          L10      09:03     NaN      09:08         False      F260019772
127           E8      08:55   08:57      09:11          True      F260019771
128          E38      08:42   08:46      09:05          True      F260019768
129           R1      08:39   08:52      08:53          True      F260019766
130           E8      08:37   08:46      08:51          True      F260019764
131          E33      08:37   08:40      08:52          True      F260019763
132          E40      08:32   08:38      08:43          True      F260019761
133          E28      08:33   08:38      08:56          True      F260019759
134          A25      08:27   08:30      08:55          True      F260019756
135          E25      08:26     NaN      08:27         False      F260019756
136          E17      08:12   08:16      08:21          True      F260019754
137          E18      08:13   08:17      08:19         False      F260019753
138          E21      08:11     NaN      08:13          True      F260019753
139          A14      08:07   08:12      08:28         False      F260019752
140          M32      08:07     NaN      08:16          True      F260019752
141           A5      07:59   08:07      08:33          True      F260019751
142           E5      07:56   08:00      08:27          True      F260019750
143          E33      07:54   07:58      08:33          True      F260019749
144          M28      07:56     NaN      08:03         False      F260019749
145          M28      08:10   08:12      09:34         False      F260019749
146           E6      07:52   07:57      07:58          True      F260019748
147           E8      07:49   07:53      08:05          True      F260019746
148          A10      10:07   10:07      10:15         False      F260019747
149           A5      09:24   09:24        NaN         False      F260019747
150          B77      09:00   09:00        NaN         False      F260019747
151          E95      08:23   08:23        NaN         False      F260019747
152      EVENT11      07:49   07:49        NaN          True      F260019747
153           A2      08:01   08:07        NaN         False      F260019745
154          E90      08:17   08:17        NaN         False      F260019745
155      EVENT13      07:48   07:48        NaN          True      F260019745
156          E26      07:47   07:52      08:02          True      F260019744
157         SQ14      07:44   07:44        NaN          True      V260019742
158      EVENT10      07:29   07:29        NaN          True      F260019740
159        HAZ80      07:34   07:34        NaN         False      F260019740
160           A5      07:17   07:26      07:41          True      F260019737
161           L1      07:17   07:23      07:36          True      F260019736
162      EVENT12      07:12   07:12        NaN          True      F260019735
163    LUMEN-CMD      08:14   08:14        NaN         False      F260019735
164          E33      07:11   07:16      07:34          True      F260019734
165          E38      07:07   07:12      07:35          True      F260019733
166          E10      06:41   06:44      06:52          True      F260019728
167           L1      06:41   06:44      06:53         False      F260019728
168           A2      06:38     NaN      06:41          True      F260019727
169          E25      06:32   06:35      06:46         False      F260019725
170          L10      06:32   06:35      06:36         False      F260019725
171           M1      06:33   06:34      07:00         False      F260019725
172          M17      06:32     NaN      06:33          True      F260019725
173          E10      06:09   06:16      06:17          True      F260019720
174          A25      06:05   06:09      06:35          True      F260019719
175           E6      06:02   06:03      06:39          True      F260019717
176           A2      05:54   06:13      06:14          True      F260019716
177          M17      05:55     NaN      06:01         False      F260019716
178           E6      05:51   05:55      05:58          True      F260019714
179          E10      05:50   05:52      05:53          True      F260019713
180           E5      05:51   05:55      06:12          True      F260019712
181           L4      05:46   05:51      06:05          True      F260019710
182          E13      05:32   05:35      05:51         False      F260019708
183          M28      05:32     NaN      05:41          True      F260019708
184          E24      05:30   05:33      05:54          True      F260019707
185           E2      05:19   05:25      05:51          True      F260019706
186           M1      05:19   05:29      06:32         False      F260019706
187          E25      05:17   05:20      05:32          True      F260019705
188          A10      05:19   05:23      05:43          True      F260019703
189           A2      05:03   05:08      05:50          True      F260019702
190          M10      05:15   05:24      05:57         False      F260019702
191          E24      04:57   05:01      05:16          True      F260019700
192          A25      04:48   04:51      04:53          True      F260019698
193          E24      04:30   04:34      04:46          True      F260019696
194           L5      04:30     NaN      04:36         False      F260019696
195           A5      04:26   04:31      04:57          True      F260019694
196          A10      04:00   04:03      04:13          True      F260019692
197          A25      03:51   03:57      04:03          True      F260019690
198           A5      03:20   03:24      03:40          True      F260019687
199          E28      03:21   03:27      03:41          True      F260019686
200          A10      03:00   03:04      03:34          True      F260019683
201          E31      02:37   02:37      03:13         False      F260019679
202           L5      02:35     NaN      02:37          True      F260019679
203          M31      02:36   02:41      03:39         False      F260019679
204           A5      02:34   02:38      02:59          True      F260019678
205          E37      02:23     NaN      02:26          True      F260019674
206          E33      02:22   02:24      02:47          True      F260019673
207          E17      02:20   02:28      02:28          True      F260019672
208          E31      02:18   02:21      02:36          True      F260019670
209           L4      02:16   02:19      02:29          True      F260019669
210           A2      02:13   02:16      02:25          True      F260019668
211           L4      02:10     NaN      02:13         False      F260019668
212           E2      02:06   02:09      02:30          True      F260019667
213           E2      01:56   02:01      02:04          True      F260019665
214           A2      01:55   02:01      02:13          True      F260019662
215          E13      01:46   01:50      02:04          True      F260019660
216          E31      01:44   01:49      01:58          True      F260019659
217           E2      01:33   01:34      01:40          True      F260019656
218           E5      01:29     NaN      01:33         False      F260019656
219          E38      01:26   01:33      01:41          True      F260019655
220          A25      01:54   02:00      02:05          True      F260019653
221           E2      01:18   01:22      01:32          True      F260019651
222           L4      01:18   01:22      01:38         False      F260019651
223          E10      01:18   01:22      01:32          True      F260019652
224           L1      01:18   01:23      01:32         False      F260019652
225          A10      01:15   01:17      01:36          True      F260019650
226           E9      01:01   01:05      01:14          True      F260019646
227          E39      01:00   01:03      01:06          True      F260019645
228           A5      00:59     NaN      01:03         False      F260019644
229           A5      01:06   01:09      01:26          True      F260019644
230           A2      00:55   00:59      01:11          True      F260019642
231           M1      00:56   01:01      01:02         False      F260019642
232          A10      00:55   00:57      01:13          True      F260019641
233          E40      00:56   01:00      01:34          True      F260019640
234          E24      00:50   00:52      01:04          True      F260019639
235           L5      00:50     NaN      00:55         False      F260019639
236          E32      00:37   00:41      01:09          True      F260019637
237          E21      00:37   00:41      00:49          True      F260019636
238          E26      00:31   00:36      00:58          True      F260019635
239          E38      00:20   00:25      00:28          True      F260019633
240          E39      00:14   00:19      00:54          True      F260019632
241          M31      00:16   00:25      00:26         False      F260019632
242          E18      00:05   00:09      00:43          True      F260019631
243           A2      00:02   00:06      00:25         False      F260019630
244          M10      00:02   00:09      00:09          True      F260019630
245           A5      23:57   00:01      00:26         False      F260019627
246           M1      23:57   00:01      00:55          True      F260019627
247          A10      23:56   23:59      00:23          True      F260019626
248          E10      23:33     NaN      23:36          True      F260019625
249           L1      23:33     NaN      23:36         False      F260019625
250          E13      23:33   23:38      23:51          True      F260019623
251           L3      23:33   23:38      23:51         False      F260019623
252          E24      23:30   23:32      23:38          True      F260019622
253           A5      23:28   23:33      23:45          True      F260019621
254          E38      23:23   23:28      00:02          True      F260019620
255          L10      23:23   23:32      23:57         False      F260019620
256          E17      23:23   23:28      23:34         False      F260019619
257           L9      23:23   23:28      23:33          True      F260019619

In [10]:
unit_dispatches_dataframe[unit_dispatches_dataframe["unit"] == "MAR5"]["time_assigned"].mean()

np.float64(39.31707317073171)

In [11]:
pd.Series([5, 4, float('nan')]).mean()

np.float64(4.5)

In [12]:
unit_list = sorted(unit_dispatches_dataframe["unit"].unique())

In [13]:
unit_dataframe = pd.DataFrame(
    columns=[
        "unit", 
        "number_of_incidents", 
        "leadership_rate", 
        "average_time_in_transit", "total_time_in_transit", 
        "average_time_on_site", "total_time_on_site", 
        "average_time_assigned", "total_time_assigned"
    ]
)

In [14]:
filtered_unit_dispatches_dataframe = unit_dispatches_dataframe[unit_dispatches_dataframe["unit"]=="A17"]

In [15]:
number_of_incidents = len(filtered_unit_dispatches_dataframe)
number_of_incidents

28

In [16]:
in_charge_counts = filtered_unit_dispatches_dataframe["is_in_charge"].value_counts()
in_charge_count = in_charge_counts.get(True) if in_charge_counts.get(True) else 0
leadership_rate = in_charge_count / number_of_incidents
leadership_rate

np.float64(0.8214285714285714)

In [17]:
average_time_in_transit = filtered_unit_dispatches_dataframe["time_in_transit"].mean()
average_time_in_transit

np.float64(5.72)

In [18]:
total_time_in_transit = filtered_unit_dispatches_dataframe["time_in_transit"].sum()
total_time_in_transit

np.float64(143.0)

In [19]:
average_time_on_site = filtered_unit_dispatches_dataframe["time_on_site"].mean()
average_time_on_site

np.float64(18.88)

In [20]:
total_time_on_site = filtered_unit_dispatches_dataframe["time_on_site"].sum()
total_time_on_site

np.float64(472.0)

In [21]:
average_time_assigned = filtered_unit_dispatches_dataframe["time_assigned"].mean()
average_time_assigned

np.float64(22.5)

In [22]:
total_time_assigned = filtered_unit_dispatches_dataframe["time_assigned"].sum()
total_time_assigned

np.float64(630.0)

In [23]:
for unit in unit_list:
    filtered_unit_dispatches_dataframe = unit_dispatches_dataframe[unit_dispatches_dataframe["unit"]==unit]
    number_of_incidents = len(filtered_unit_dispatches_dataframe)
    in_charge_counts = filtered_unit_dispatches_dataframe["is_in_charge"].value_counts()
    in_charge_count = in_charge_counts.get(True) if in_charge_counts.get(True) else 0
    leadership_rate = in_charge_count / number_of_incidents
    average_time_in_transit = filtered_unit_dispatches_dataframe["time_in_transit"].mean()
    total_time_in_transit = filtered_unit_dispatches_dataframe["time_in_transit"].sum()
    average_time_on_site = filtered_unit_dispatches_dataframe["time_on_site"].mean()
    total_time_on_site = filtered_unit_dispatches_dataframe["time_on_site"].sum()
    average_time_assigned = filtered_unit_dispatches_dataframe["time_assigned"].mean()
    total_time_assigned = filtered_unit_dispatches_dataframe["time_assigned"].sum()
    new_row = {
        'unit': unit, 
        'number_of_incidents': number_of_incidents,
        'leadership_rate': leadership_rate,
        'average_time_in_transit': average_time_in_transit,
        'total_time_in_transit': total_time_in_transit,
        'average_time_on_site': average_time_on_site,
        'total_time_on_site': total_time_on_site,
        'average_time_assigned': average_time_assigned,
        'total_time_assigned': total_time_assigned,
    }
    unit_dataframe = pd.concat([unit_dataframe, pd.DataFrame([new_row])], ignore_index=True)

In [24]:
unit_dataframe

,unit,number_of_incidents,leadership_rate,average_time_in_transit,total_time_in_transit,average_time_on_site,total_time_on_site,average_time_assigned,total_time_assigned
0,A10,460,0.791304,4.238663,1776.0,21.406699,8948.0,23.714597,10885.0
1,A14,109,0.688073,6.163636,339.0,18.727273,1030.0,14.926606,1627.0
2,A17,28,0.821429,5.72,143.0,18.88,472.0,22.5,630.0
3,A2,486,0.771605,4.706731,1958.0,17.595181,7302.0,19.523711,9469.0
4,A22,3,1.0,6.0,18.0,31.0,93.0,37.0,111.0
5,A25,483,0.786749,4.816555,2153.0,18.955257,8473.0,22.395445,10817.0
6,A26,2,1.0,5.0,5.0,NaN,0.0,1.0,1.0
7,A31,153,0.745098,5.577465,792.0,20.626761,2929.0,24.633987,3769.0
8,A4,305,0.75082,4.44,1221.0,19.338182,5318.0,21.721311,6625.0
9,A5,461,0.772234,4.949029,2039.0,19.048662,7829.0,22.054348,10145.0
10,A7,49,0.836735,6.422222,289.0,22.888889,1030.0,27.22449,1334.0
11,AIR1,1,0.0,NaN,0.0,NaN,0.0,5.0,5.0
12,AIR10,34,0.0,17.416667,209.0,53.25,639.0,68.676471,2335.0
13,AIR26,1,0.0,NaN,0.0,NaN,0.0,6.0,6.0
14,B2,94,0.010638,6.338983,374.0,41.610169,2455.0,32.276596,3034.0
15,B4,44,0.022727,8.727273,192.0,34.545455,760.0,24.704545,1087.0
16,B5,67,0.0,7.804878,320.0,15.707317,644.0,16.850746,1129.0
17,B6,61,0.016393,7.822222,352.0,20.6,927.0,22.606557,1379.0
18,B7,34,0.029412,6.478261,149.0,25.217391,580.0,23.147059,787.0
19,B77,1,0.0,0.0,0.0,NaN,0.0,NaN,0.0
20,CHAP5,9,0.0,104.5,209.0,1351.0,1351.0,195.75,1566.0
21,CHAP6,1,0.0,NaN,0.0,NaN,0.0,62.0,62.0
22,CHAP7,1,0.0,NaN,0.0,NaN,0.0,159.0,159.0
23,DECON1,8,0.0,15.0,15.0,49.0,49.0,20.75,166.0
24,DEP1,34,0.0,8.625,138.0,25.6875,411.0,20.470588,696.0
25,E10,327,0.752294,4.384058,1210.0,19.087273,5249.0,20.365031,6639.0
26,E11,137,0.839416,5.350746,717.0,16.932836,2269.0,21.934307,3005.0
27,E13,223,0.7713,5.306931,1072.0,15.990099,3230.0,19.726457,4399.0
28,E16,178,0.780899,4.993548,774.0,20.296774,3146.0,22.870787,4071.0
29,E17,345,0.846377,4.564103,1424.0,16.083333,5018.0,18.927536,6530.0
30,E18,265,0.807547,4.298755,1036.0,16.970833,4073.0,19.579545,5169.0
31,E2,385,0.761039,4.716867,1566.0,13.76506,4570.0,16.345455,6293.0
32,E20,116,0.818966,4.80198,485.0,20.475248,2068.0,22.551724,2616.0
33,E21,167,0.784431,4.414966,649.0,16.780822,2450.0,19.151515,3160.0
34,E22,87,0.724138,6.105263,464.0,20.078947,1526.0,23.45977,2041.0
35,E24,293,0.819113,4.523297,1262.0,19.688172,5493.0,23.228669,6806.0
36,E25,374,0.772727,4.35873,1373.0,16.866667,5313.0,18.245989,6824.0
37,E26,75,0.786667,4.820896,323.0,20.179104,1352.0,22.973333,1723.0
38,E27,104,0.605769,5.494253,478.0,20.241379,1761.0,22.557692,2346.0
39,E28,307,0.807818,4.589474,1308.0,19.350877,5515.0,22.394137,6875.0
40,E29,129,0.813953,5.411765,644.0,23.09322,2725.0,26.671875,3414.0
41,E30,285,0.803509,4.0,1052.0,19.528517,5136.0,22.178947,6321.0
42,E31,270,0.777778,4.970588,1183.0,17.647059,4200.0,20.359259,5497.0
43,E32,192,0.78125,4.780347,827.0,19.578035,3387.0,22.255208,4273.0
44,E33,196,0.836735,4.211957,775.0,18.603261,3423.0,21.719388,4257.0
45,E34,111,0.828829,4.793814,465.0,18.552083,1781.0,20.618182,2268.0
46,E35,157,0.802548,5.155556,696.0,20.837037,2813.0,23.0,3611.0
47,E36,104,0.673077,6.27907,540.0,22.755814,1957.0,24.894231,2589.0
48,E37,202,0.806931,5.26776,964.0,19.690608,3564.0,22.875,4575.0
49,E38,188,0.824468,5.0625,891.0,20.573864,3621.0,24.308511,4570.0
50,E39,220,0.872727,5.371429,1128.0,20.47619,4300.0,25.054545,5512.0
51,E40,146,0.753425,5.117188,655.0,20.0625,2568.0,22.655172,3285.0
52,E41,75,0.893333,5.410959,395.0,21.166667,1524.0,25.810811,1910.0
53,E5,261,0.724138,4.64574,1036.0,17.7713,3963.0,19.777778,5162.0
54,E6,321,0.775701,4.114379,1259.0,17.571895,5377.0,20.965732,6730.0
55,E8,177,0.847458,5.221519,825.0,17.012739,2671.0,20.340909,3580.0
56,E9,199,0.778894,4.681564,838.0,18.703911,3348.0,21.417085,4262.0
57,E90,1,0.0,0.0,0.0,NaN,0.0,NaN,0.0
58,E95,1,0.0,0.0,0.0,NaN,0.0,NaN,0.0
59,EVENT1,1,1.0,0.0,0.0,NaN,0.0,NaN,0.0
60,EVENT10,1,1.0,0.0,0.0,NaN,0.0,NaN,0.0
61,EVENT11,3,1.0,0.0,0.0,NaN,0.0,NaN,0.0
62,EVENT12,13,0.846154,0.384615,5.0,4.0,4.0,4.0,4.0
63,EVENT13,14,0.785714,0.0,0.0,NaN,0.0,NaN,0.0
64,EVENT14,9,0.888889,0.0,0.0,204.6,1023.0,204.6,1023.0
65,EVENT15,1,1.0,0.0,0.0,NaN,0.0,NaN,0.0
66,EVENT2,1,1.0,1.0,1.0,NaN,0.0,NaN,0.0
67,EVENT3,1,1.0,0.0,0.0,NaN,0.0,NaN,0.0
68,EVENT4,1,1.0,0.0,0.0,NaN,0.0,NaN,0.0
69,EVENT5,1,1.0,0.0,0.0,NaN,0.0,NaN,0.0
70,EVENT6,1,1.0,0.0,0.0,NaN,0.0,NaN,0.0
71,FAC,5,0.6,0.0,0.0,3.0,3.0,1.4,7.0
72,FAC1,8,0.75,0.0,0.0,11.0,11.0,5.0,40.0
73,FB1,6,0.166667,13.666667,41.0,32.666667,98.0,26.333333,158.0
74,FB3,3,0.0,49.0,49.0,39.0,39.0,32.333333,97.0
75,FB4,1,0.0,0.0,0.0,101.0,101.0,101.0,101.0
76,FIREBOAT,18,0.166667,0.0,0.0,11.0,33.0,6.277778,113.0
77,H1,88,0.784091,13.25,1060.0,31.6,2528.0,41.943182,3691.0
78,H11,2,0.0,28.0,28.0,1.0,1.0,37.0,74.0
79,H2,41,0.853659,12.081081,447.0,42.864865,1586.0,63.195122,2591.0
80,H98,37,0.72973,7.666667,230.0,33.366667,1001.0,33.864865,1253.0
81,H99,91,0.043956,6.376623,491.0,22.61039,1741.0,25.0,2275.0
82,HAZ1,8,0.0,12.8,64.0,63.0,252.0,46.0,322.0
83,HAZ80,2,0.0,0.0,0.0,NaN,0.0,NaN,0.0
84,HUSKY-EMS,4,0.0,0.0,0.0,206.333333,619.0,206.333333,619.0
85,L1,235,0.310638,5.219251,976.0,15.521505,2887.0,17.307692,4050.0
86,L10,250,0.312,4.680628,894.0,21.747368,4132.0,21.064257,5245.0
87,L11,98,0.418367,5.618421,427.0,24.223684,1841.0,24.05102,2357.0
88,L12,159,0.471698,5.590164,682.0,15.959016,1947.0,17.339623,2757.0
89,L13,96,0.583333,5.736111,413.0,20.492958,1455.0,20.8,1976.0
90,L3,194,0.417526,5.272727,812.0,23.253247,3581.0,23.329897,4526.0
91,L4,264,0.337121,5.477833,1112.0,12.940887,2627.0,14.920455,3939.0
92,L5,183,0.382514,7.479339,905.0,15.07438,1824.0,16.68306,3053.0
93,L6,110,0.372727,6.565789,499.0,17.64,1323.0,18.211009,1985.0
94,L8,168,0.458333,7.0,847.0,16.53719,2001.0,18.136905,3047.0
95,L9,222,0.355856,5.927273,978.0,15.163636,2502.0,17.067568,3789.0
96,LUMEN-CMD,1,0.0,0.0,0.0,NaN,0.0,NaN,0.0
97,LUMEN-EMS,2,0.0,2.5,5.0,NaN,0.0,NaN,0.0
98,LUMEN-HAZ,1,0.0,0.0,0.0,NaN,0.0,NaN,0.0
99,M1,367,0.444142,7.042308,1831.0,36.223077,9418.0,32.152589,11800.0
100,M10,334,0.449102,7.254386,1654.0,39.872807,9091.0,33.694611,11254.0
101,M17,254,0.374016,7.791411,1270.0,36.472393,5945.0,30.366142,7713.0
102,M18,142,0.373239,8.065217,742.0,43.945652,4043.0,35.316901,5015.0
103,M26,51,0.392157,8.058824,274.0,41.424242,1367.0,34.62,1731.0
104,M28,184,0.407609,7.215278,1039.0,44.486111,6406.0,41.63587,7661.0
105,M31,156,0.461538,7.832,979.0,51.942623,6337.0,48.392157,7404.0
106,M32,161,0.453416,7.798246,889.0,44.938596,5123.0,39.043478,6286.0
107,M44,92,0.0,8.708333,418.0,19.458333,934.0,18.934783,1742.0
108,MAR5,42,0.0,19.363636,426.0,45.454545,1000.0,39.317073,1612.0
109,MIH,60,0.033333,19.0,38.0,0.0,0.0,9.883333,593.0
110,MRN1,4,0.0,27.5,55.0,87.5,175.0,61.0,244.0
111,MVU1,4,0.0,26.333333,79.0,62.0,186.0,72.5,290.0
112,NOR-M163,4,0.0,16.5,33.0,103.0,206.0,60.5,242.0
113,PIO,1,0.0,NaN,0.0,NaN,0.0,7.0,7.0
114,PIO2,3,0.0,5.666667,17.0,39.0,78.0,39.0,78.0
115,PLEDG-EMS,13,0.230769,0.0,0.0,NaN,0.0,NaN,0.0
116,PTRL4,6,0.0,NaN,0.0,NaN,0.0,17.833333,107.0
117,R1,123,0.252033,7.64557,604.0,19.405063,1533.0,19.487805,2397.0
118,RB5,2,0.0,20.0,40.0,66.0,132.0,86.0,172.0
119,REHAB1,27,0.037037,13.857143,97.0,18.0,126.0,14.296296,386.0
120,SAFT2,66,0.0,10.878788,359.0,24.060606,794.0,20.818182,1374.0
121,SQ14,3,1.0,0.0,0.0,NaN,0.0,NaN,0.0
122,STAF10,34,0.0,11.25,180.0,32.0625,513.0,24.705882,840.0
123,TMOB-EMS,2,0.0,0.0,0.0,NaN,0.0,NaN,0.0
124,WAMU-EMS,6,0.333333,0.0,0.0,1.0,1.0,1.0,1.0

In [25]:
unit_dataframe.to_excel("unit_stats_last_30_days.xlsx")

Leadership rate should never be greater than 1, something is wrong.